/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicosSlugRouteImport } from './routes/servicos.$slug'
import { Route as EventoSlugRouteImport } from './routes/evento.$slug'
import { Route as ClubeSucessoRouteImport } from './routes/clube.sucesso'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiWebhooksHublaRouteImport } from './routes/api.webhooks.hubla'
import { Route as AuthenticatedPortalServicosRouteImport } from './routes/_authenticated/portal.servicos'
import { Route as AuthenticatedPortalLojaRouteImport } from './routes/_authenticated/portal.loja'
import { Route as AuthenticatedPortalIngressosRouteImport } from './routes/_authenticated/portal.ingressos'
import { Route as AuthenticatedPortalClubeRouteImport } from './routes/_authenticated/portal.clube'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminTriagemRouteImport } from './routes/_authenticated/admin.triagem'
import { Route as AuthenticatedAdminSlotsRouteImport } from './routes/_authenticated/admin.slots'
import { Route as AuthenticatedAdminRelatoriosRouteImport } from './routes/_authenticated/admin.relatorios'
import { Route as AuthenticatedAdminPdvRouteImport } from './routes/_authenticated/admin.pdv'
import { Route as AuthenticatedAdminFinanceiroRouteImport } from './routes/_authenticated/admin.financeiro'
import { Route as AuthenticatedAdminEventosRouteImport } from './routes/_authenticated/admin.eventos'
import { Route as AuthenticatedAdminEsteiraRouteImport } from './routes/_authenticated/admin.esteira'
import { Route as AuthenticatedAdminCrmRouteImport } from './routes/_authenticated/admin.crm'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminClubeRouteImport } from './routes/_authenticated/admin.clube'
import { Route as AuthenticatedAdminAutomacoesRouteImport } from './routes/_authenticated/admin.automacoes'
import { Route as AuthenticatedAdminAgendaRouteImport } from './routes/_authenticated/admin.agenda'
import { Route as AuthenticatedAdminAcessoNegadoRouteImport } from './routes/_authenticated/admin.acesso-negado'

const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosSlugRoute = ServicosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicosRoute,
} as any)
const EventoSlugRoute = EventoSlugRouteImport.update({
  id: '/evento/$slug',
  path: '/evento/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubeSucessoRoute = ClubeSucessoRouteImport.update({
  id: '/clube/sucesso',
  path: '/clube/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiWebhooksHublaRoute = ApiWebhooksHublaRouteImport.update({
  id: '/api/webhooks/hubla',
  path: '/api/webhooks/hubla',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalServicosRoute =
  AuthenticatedPortalServicosRouteImport.update({
    id: '/servicos',
    path: '/servicos',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalLojaRoute = AuthenticatedPortalLojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => AuthenticatedPortalRoute,
} as any)
const AuthenticatedPortalIngressosRoute =
  AuthenticatedPortalIngressosRouteImport.update({
    id: '/ingressos',
    path: '/ingressos',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalClubeRoute =
  AuthenticatedPortalClubeRouteImport.update({
    id: '/clube',
    path: '/clube',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTriagemRoute =
  AuthenticatedAdminTriagemRouteImport.update({
    id: '/triagem',
    path: '/triagem',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSlotsRoute = AuthenticatedAdminSlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRelatoriosRoute =
  AuthenticatedAdminRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPdvRoute = AuthenticatedAdminPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminFinanceiroRoute =
  AuthenticatedAdminFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosRoute =
  AuthenticatedAdminEventosRouteImport.update({
    id: '/eventos',
    path: '/eventos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEsteiraRoute =
  AuthenticatedAdminEsteiraRouteImport.update({
    id: '/esteira',
    path: '/esteira',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCrmRoute = AuthenticatedAdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClubeRoute = AuthenticatedAdminClubeRouteImport.update({
  id: '/clube',
  path: '/clube',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAutomacoesRoute =
  AuthenticatedAdminAutomacoesRouteImport.update({
    id: '/automacoes',
    path: '/automacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAgendaRoute =
  AuthenticatedAdminAgendaRouteImport.update({
    id: '/agenda',
    path: '/agenda',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAcessoNegadoRoute =
  AuthenticatedAdminAcessoNegadoRouteImport.update({
    id: '/acesso-negado',
    path: '/acesso-negado',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/clube/sucesso': typeof ClubeSucessoRoute
  '/evento/$slug': typeof EventoSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/admin/acesso-negado': typeof AuthenticatedAdminAcessoNegadoRoute
  '/admin/agenda': typeof AuthenticatedAdminAgendaRoute
  '/admin/automacoes': typeof AuthenticatedAdminAutomacoesRoute
  '/admin/clube': typeof AuthenticatedAdminClubeRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/admin/esteira': typeof AuthenticatedAdminEsteiraRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/pdv': typeof AuthenticatedAdminPdvRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/slots': typeof AuthenticatedAdminSlotsRoute
  '/admin/triagem': typeof AuthenticatedAdminTriagemRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/portal/clube': typeof AuthenticatedPortalClubeRoute
  '/portal/ingressos': typeof AuthenticatedPortalIngressosRoute
  '/portal/loja': typeof AuthenticatedPortalLojaRoute
  '/portal/servicos': typeof AuthenticatedPortalServicosRoute
  '/api/webhooks/hubla': typeof ApiWebhooksHublaRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/clube/sucesso': typeof ClubeSucessoRoute
  '/evento/$slug': typeof EventoSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/admin/acesso-negado': typeof AuthenticatedAdminAcessoNegadoRoute
  '/admin/agenda': typeof AuthenticatedAdminAgendaRoute
  '/admin/automacoes': typeof AuthenticatedAdminAutomacoesRoute
  '/admin/clube': typeof AuthenticatedAdminClubeRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/admin/esteira': typeof AuthenticatedAdminEsteiraRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/pdv': typeof AuthenticatedAdminPdvRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/slots': typeof AuthenticatedAdminSlotsRoute
  '/admin/triagem': typeof AuthenticatedAdminTriagemRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/portal/clube': typeof AuthenticatedPortalClubeRoute
  '/portal/ingressos': typeof AuthenticatedPortalIngressosRoute
  '/portal/loja': typeof AuthenticatedPortalLojaRoute
  '/portal/servicos': typeof AuthenticatedPortalServicosRoute
  '/api/webhooks/hubla': typeof ApiWebhooksHublaRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/clube/sucesso': typeof ClubeSucessoRoute
  '/evento/$slug': typeof EventoSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/_authenticated/admin/acesso-negado': typeof AuthenticatedAdminAcessoNegadoRoute
  '/_authenticated/admin/agenda': typeof AuthenticatedAdminAgendaRoute
  '/_authenticated/admin/automacoes': typeof AuthenticatedAdminAutomacoesRoute
  '/_authenticated/admin/clube': typeof AuthenticatedAdminClubeRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/_authenticated/admin/esteira': typeof AuthenticatedAdminEsteiraRoute
  '/_authenticated/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/_authenticated/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/_authenticated/admin/pdv': typeof AuthenticatedAdminPdvRoute
  '/_authenticated/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/_authenticated/admin/slots': typeof AuthenticatedAdminSlotsRoute
  '/_authenticated/admin/triagem': typeof AuthenticatedAdminTriagemRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/portal/clube': typeof AuthenticatedPortalClubeRoute
  '/_authenticated/portal/ingressos': typeof AuthenticatedPortalIngressosRoute
  '/_authenticated/portal/loja': typeof AuthenticatedPortalLojaRoute
  '/_authenticated/portal/servicos': typeof AuthenticatedPortalServicosRoute
  '/api/webhooks/hubla': typeof ApiWebhooksHublaRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/servicos'
    | '/admin'
    | '/portal'
    | '/clube/sucesso'
    | '/evento/$slug'
    | '/servicos/$slug'
    | '/admin/acesso-negado'
    | '/admin/agenda'
    | '/admin/automacoes'
    | '/admin/clube'
    | '/admin/configuracoes'
    | '/admin/crm'
    | '/admin/esteira'
    | '/admin/eventos'
    | '/admin/financeiro'
    | '/admin/pdv'
    | '/admin/relatorios'
    | '/admin/slots'
    | '/admin/triagem'
    | '/admin/usuarios'
    | '/portal/clube'
    | '/portal/ingressos'
    | '/portal/loja'
    | '/portal/servicos'
    | '/api/webhooks/hubla'
    | '/admin/'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/servicos'
    | '/clube/sucesso'
    | '/evento/$slug'
    | '/servicos/$slug'
    | '/admin/acesso-negado'
    | '/admin/agenda'
    | '/admin/automacoes'
    | '/admin/clube'
    | '/admin/configuracoes'
    | '/admin/crm'
    | '/admin/esteira'
    | '/admin/eventos'
    | '/admin/financeiro'
    | '/admin/pdv'
    | '/admin/relatorios'
    | '/admin/slots'
    | '/admin/triagem'
    | '/admin/usuarios'
    | '/portal/clube'
    | '/portal/ingressos'
    | '/portal/loja'
    | '/portal/servicos'
    | '/api/webhooks/hubla'
    | '/admin'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/servicos'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/clube/sucesso'
    | '/evento/$slug'
    | '/servicos/$slug'
    | '/_authenticated/admin/acesso-negado'
    | '/_authenticated/admin/agenda'
    | '/_authenticated/admin/automacoes'
    | '/_authenticated/admin/clube'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/crm'
    | '/_authenticated/admin/esteira'
    | '/_authenticated/admin/eventos'
    | '/_authenticated/admin/financeiro'
    | '/_authenticated/admin/pdv'
    | '/_authenticated/admin/relatorios'
    | '/_authenticated/admin/slots'
    | '/_authenticated/admin/triagem'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/portal/clube'
    | '/_authenticated/portal/ingressos'
    | '/_authenticated/portal/loja'
    | '/_authenticated/portal/servicos'
    | '/api/webhooks/hubla'
    | '/_authenticated/admin/'
    | '/_authenticated/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ServicosRoute: typeof ServicosRouteWithChildren
  ClubeSucessoRoute: typeof ClubeSucessoRoute
  EventoSlugRoute: typeof EventoSlugRoute
  ApiWebhooksHublaRoute: typeof ApiWebhooksHublaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/$slug': {
      id: '/servicos/$slug'
      path: '/$slug'
      fullPath: '/servicos/$slug'
      preLoaderRoute: typeof ServicosSlugRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/evento/$slug': {
      id: '/evento/$slug'
      path: '/evento/$slug'
      fullPath: '/evento/$slug'
      preLoaderRoute: typeof EventoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clube/sucesso': {
      id: '/clube/sucesso'
      path: '/clube/sucesso'
      fullPath: '/clube/sucesso'
      preLoaderRoute: typeof ClubeSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/webhooks/hubla': {
      id: '/api/webhooks/hubla'
      path: '/api/webhooks/hubla'
      fullPath: '/api/webhooks/hubla'
      preLoaderRoute: typeof ApiWebhooksHublaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/servicos': {
      id: '/_authenticated/portal/servicos'
      path: '/servicos'
      fullPath: '/portal/servicos'
      preLoaderRoute: typeof AuthenticatedPortalServicosRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/loja': {
      id: '/_authenticated/portal/loja'
      path: '/loja'
      fullPath: '/portal/loja'
      preLoaderRoute: typeof AuthenticatedPortalLojaRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/ingressos': {
      id: '/_authenticated/portal/ingressos'
      path: '/ingressos'
      fullPath: '/portal/ingressos'
      preLoaderRoute: typeof AuthenticatedPortalIngressosRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/clube': {
      id: '/_authenticated/portal/clube'
      path: '/clube'
      fullPath: '/portal/clube'
      preLoaderRoute: typeof AuthenticatedPortalClubeRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/triagem': {
      id: '/_authenticated/admin/triagem'
      path: '/triagem'
      fullPath: '/admin/triagem'
      preLoaderRoute: typeof AuthenticatedAdminTriagemRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/slots': {
      id: '/_authenticated/admin/slots'
      path: '/slots'
      fullPath: '/admin/slots'
      preLoaderRoute: typeof AuthenticatedAdminSlotsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/relatorios': {
      id: '/_authenticated/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AuthenticatedAdminRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pdv': {
      id: '/_authenticated/admin/pdv'
      path: '/pdv'
      fullPath: '/admin/pdv'
      preLoaderRoute: typeof AuthenticatedAdminPdvRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/financeiro': {
      id: '/_authenticated/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos': {
      id: '/_authenticated/admin/eventos'
      path: '/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AuthenticatedAdminEventosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/esteira': {
      id: '/_authenticated/admin/esteira'
      path: '/esteira'
      fullPath: '/admin/esteira'
      preLoaderRoute: typeof AuthenticatedAdminEsteiraRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/crm': {
      id: '/_authenticated/admin/crm'
      path: '/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AuthenticatedAdminCrmRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clube': {
      id: '/_authenticated/admin/clube'
      path: '/clube'
      fullPath: '/admin/clube'
      preLoaderRoute: typeof AuthenticatedAdminClubeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/automacoes': {
      id: '/_authenticated/admin/automacoes'
      path: '/automacoes'
      fullPath: '/admin/automacoes'
      preLoaderRoute: typeof AuthenticatedAdminAutomacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/agenda': {
      id: '/_authenticated/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AuthenticatedAdminAgendaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/acesso-negado': {
      id: '/_authenticated/admin/acesso-negado'
      path: '/acesso-negado'
      fullPath: '/admin/acesso-negado'
      preLoaderRoute: typeof AuthenticatedAdminAcessoNegadoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAcessoNegadoRoute: typeof AuthenticatedAdminAcessoNegadoRoute
  AuthenticatedAdminAgendaRoute: typeof AuthenticatedAdminAgendaRoute
  AuthenticatedAdminAutomacoesRoute: typeof AuthenticatedAdminAutomacoesRoute
  AuthenticatedAdminClubeRoute: typeof AuthenticatedAdminClubeRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminCrmRoute: typeof AuthenticatedAdminCrmRoute
  AuthenticatedAdminEsteiraRoute: typeof AuthenticatedAdminEsteiraRoute
  AuthenticatedAdminEventosRoute: typeof AuthenticatedAdminEventosRoute
  AuthenticatedAdminFinanceiroRoute: typeof AuthenticatedAdminFinanceiroRoute
  AuthenticatedAdminPdvRoute: typeof AuthenticatedAdminPdvRoute
  AuthenticatedAdminRelatoriosRoute: typeof AuthenticatedAdminRelatoriosRoute
  AuthenticatedAdminSlotsRoute: typeof AuthenticatedAdminSlotsRoute
  AuthenticatedAdminTriagemRoute: typeof AuthenticatedAdminTriagemRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAcessoNegadoRoute: AuthenticatedAdminAcessoNegadoRoute,
  AuthenticatedAdminAgendaRoute: AuthenticatedAdminAgendaRoute,
  AuthenticatedAdminAutomacoesRoute: AuthenticatedAdminAutomacoesRoute,
  AuthenticatedAdminClubeRoute: AuthenticatedAdminClubeRoute,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminCrmRoute: AuthenticatedAdminCrmRoute,
  AuthenticatedAdminEsteiraRoute: AuthenticatedAdminEsteiraRoute,
  AuthenticatedAdminEventosRoute: AuthenticatedAdminEventosRoute,
  AuthenticatedAdminFinanceiroRoute: AuthenticatedAdminFinanceiroRoute,
  AuthenticatedAdminPdvRoute: AuthenticatedAdminPdvRoute,
  AuthenticatedAdminRelatoriosRoute: AuthenticatedAdminRelatoriosRoute,
  AuthenticatedAdminSlotsRoute: AuthenticatedAdminSlotsRoute,
  AuthenticatedAdminTriagemRoute: AuthenticatedAdminTriagemRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalClubeRoute: typeof AuthenticatedPortalClubeRoute
  AuthenticatedPortalIngressosRoute: typeof AuthenticatedPortalIngressosRoute
  AuthenticatedPortalLojaRoute: typeof AuthenticatedPortalLojaRoute
  AuthenticatedPortalServicosRoute: typeof AuthenticatedPortalServicosRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalClubeRoute: AuthenticatedPortalClubeRoute,
  AuthenticatedPortalIngressosRoute: AuthenticatedPortalIngressosRoute,
  AuthenticatedPortalLojaRoute: AuthenticatedPortalLojaRoute,
  AuthenticatedPortalServicosRoute: AuthenticatedPortalServicosRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ServicosRouteChildren {
  ServicosSlugRoute: typeof ServicosSlugRoute
}

const ServicosRouteChildren: ServicosRouteChildren = {
  ServicosSlugRoute: ServicosSlugRoute,
}

const ServicosRouteWithChildren = ServicosRoute._addFileChildren(
  ServicosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ServicosRoute: ServicosRouteWithChildren,
  ClubeSucessoRoute: ClubeSucessoRoute,
  EventoSlugRoute: EventoSlugRoute,
  ApiWebhooksHublaRoute: ApiWebhooksHublaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
