// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'
import { getImpersonatedUserIdHeader } from '@/lib/impersonation'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token
    const impersonatedUserId = getImpersonatedUserIdHeader()
    return next({
      headers: {
        ...(token ? { Authorization: `Bearer ${token}` } : {}),
        ...(impersonatedUserId ? { 'X-Empuria-Impersonate-User-Id': impersonatedUserId } : {}),
      },
    })
  },
)
