// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymbqezywautqnjhsrlit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltYnFlenl3YXV0cW5qaHNybGl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk0NDg3MzIsImV4cCI6MjA5NTAyNDczMn0.SR_faXSZi3dycGHtrXw4brb0Q7YVrvHB2GCFwaK7-dg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});